# Generated by Django 6.0.3 on 2026-03-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
