# Generated by Django 6.0.3 on 2026-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
