# Generated by Django 6.0.3 on 2026-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_seo_description_tool_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
